version: "3"
services:
  backend:
    container_name: DJANGO_SERVER
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/beside_project
      - static_volume:/static/file
    env_file:
      - .env
    command: bash ./build.sh

  prod_backend:
    container_name: PROD_SERVER
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/beside_project
      - static_volume:/static/staticfiles
    env_file:
      - .env
    environment:
      SERVER: "prod"

    command: bash ./prod_build.sh

  nginx:
    container_name: NGINX
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      args:
        SERVER: ${SERVER}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/static/staticfiles
    depends_on:
      - backend
      - prod_backend

  postgres:
    container_name: POSTGRES_DB
    image: postgres:latest
    environment:
      POSTGRES_USER: miimgoo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: miimgoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
