version: "3"
services:
  backend:
    container_name: DJANGO_SERVER
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/beside_project
      - static_volume:/static/file
    env_file:
      - .env
    command: bash ./build.sh

  nginx:
    container_name: NGINX
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      args:
        SERVER: ${SERVER}
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static/file
    depends_on:
      - backend

volumes:
  static_volume:
