version: "3"
services:
  backend:
    container_name: DJANGO_SERVER
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/beside_project
    env_file:
      - .env
    command: bash /beside_project/build.sh
