# Generated by Django 4.2.4 on 2023-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('situation', '상황'), ('emotion', '감정'), ('character', '인물'), ('other', '기타')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
