# Generated by Django 4.2.4 on 2023-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_rename_tags_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("상황", "상황"), ("감정", "감정"), ("인물", "인물"), ("기타", "기타")],
                max_length=100,
            ),
        ),
    ]
