# Generated by Django 4.2.4 on 2023-08-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_alter_tag_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "type")},
        ),
    ]
