# Generated by Django 4.2.4 on 2023-08-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0002_meme_delete_memes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meme",
            old_name="meme_gif",
            new_name="meme_url",
        ),
    ]
