name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t django:test --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} .

      - name: Run Pytest in Docker container
        run: docker run --rm django:test pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: SSH to Naver Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAVER_CLOUD_HOST }}
          username: ${{ secrets.NAVER_CLOUD_USERNAME }}
          password: ${{ secrets.NAVER_CLOUD_PASSWORD }}
          port: ${{ secrets.NAVER_CLOUD_PORT }}
          script: |
            cd beside_project
            git pull origin main
            docker-compose up --build -d
